import { StarknetProvider } from "@/lib/starknetProvider";
import { Inter } from "next/font/google";
import Header from "@/components/Header";

export const metadata = {
  title: "Carmine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StarknetProvider>
      <Header />
      {children}
    </StarknetProvider>
  );
}
