import "@/styles/globals.css";
import { Inter, Yeseva_One } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const yeseva_one = Yeseva_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-yeseva-one",
});

export const metadata = {
  title: "Carmine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${yeseva_one.variable}`}>
        {children}
      </body>
    </html>
  );
}
